### ISSUE TITLE
The library prints to the console

### ISSUE THREAD

**Issue by ssorj** [jms-ra/generic-jms-ra#26]
https://github.com/jms-ra/generic-jms-ra/blob/235af0a0a507393580a9c121173037c6a45c8f7e/generic-jms-ra-jar/src/main/java/org/jboss/resource/adapter/jms/JmsConnectionFactoryImpl.java#L234

Found this during some testing.  It looks like it was left there unintentionally.

**Comment by Ladicek** [comment]
Agree this should be removed. Or made a TRACE-level log.
